export const SVG_QUALITY_RULES = `SVG QUALITY CONTRACT
- Plan before drawing: identify the learning question, all required entities, labels, stages, relationships, values, units, legends, conditions, and exceptions. Choose a flow, cycle, hierarchy, timeline, comparison, or chart that matches that meaning. Do not turn unrelated facts into a flow just to add arrows.
- Write a coverage checklist privately, then allocate a grid and text boxes. Draw connectors behind nodes; route arrows around labels and terminate them at node edges. Show arrow direction and label non-obvious relationships. Use identical geometry for equivalent items.
- Build a complete educational figure, not placeholder artwork: include a short visible title, meaningful labels, any necessary legend, and a nearby explanatory takeaway. Preserve every detail needed to interpret it, including chart axes, units, tick values, scale, branches, and qualifications. Use native text or a table below the figure for long explanations and exact data.
- Design for a 720-960 unit viewBox, at least 28 units of outer padding, 20-32 units of gaps, 24-32 unit headings, and 18-22 unit labels. Budget text width conservatively at about 0.6 * font-size * character-count. Wrap with explicit x/y or dy tspans and 1.3 line spacing. Expand boxes and height; split complex figures into titled panels instead of squeezing content or shrinking labels.
- Use a white or warm near-white background, dark text, 2-3 purposeful accent colors, consistent stroke widths and corner radii. Never rely on color alone. Keep all labels, strokes and arrowheads inside the viewBox, with no overlapping text. Use an ordinary Arial/sans-serif font stack and explicit fill/stroke/font attributes.
- Emit one valid SVG root per :::svg block with xmlns and a positive viewBox. Close every element. Escape XML ampersands as &amp; and less-than signs as &lt;. Avoid HTML, foreignObject, scripts, remote assets, CSS stylesheets, animations, filters, and unsupported attributes. Use simple polygons for arrows or locally defined markers with unique IDs prefixed for each figure. Every local reference must exist.
- Before returning, perform two private passes: (1) compare every fact and relationship against the source or reliable topic knowledge; (2) check bounds, estimated label widths, contrast, connector routing, referenced IDs, and all closing SVG/MMD tags. Redesign any failing figure. Never claim a visual was rendered or inspected if you could not actually render it.`;

export function visualStyleRules(style: string): string {
  return style === "visual_creative"
    ? `VISUAL & CREATIVE DEPTH\nMake purposeful visuals a primary teaching tool. For each major concept that benefits from spatial explanation, build a polished, information-rich SVG with a visible title and a complete explanation nearby. A substantial multi-topic guide usually needs multiple focused figures, not one token diagram. Prefer mechanism diagrams, annotated comparisons and multi-stage systems over decorative cards. Keep all important information readable as prose or tables too. Depth and accuracy take precedence over a fixed diagram count.`
    : `INFORMATION-FIRST VISUALS\nPrioritize complete explanations at the selected level of detail. Include a focused SVG when a process, relationship, comparison, hierarchy or timeline becomes clearer visually; do not reserve SVGs for Visual & Creative mode. Apply the same SVG quality contract, with fewer figures and more emphasis on prose, worked examples and factual coverage. Never force a diagram for material that has no useful visual structure.`;
}
