"use client";

import { useEffect, useState } from "react";
import { Loader2, Workflow } from "lucide-react";
import type { MmdBlockNode } from "@/lib/mmd/ast";
import { useMmdRenderContext } from "@/components/mmd/render-context";

import { diagramToSvg } from "@/lib/diagrams/svg";
import { diagramDataSchema } from "@/lib/diagrams/schema";

type ResolveState = "loading" | "found" | "not-found";

/**
 * :::diagram{id="..." caption="..."}
 *
 * Resolves against the real /api/diagrams/:id endpoint now that the
 * diagram data layer exists (lib/diagrams/repo.ts, prisma Diagram model —
 * see .context/diagram-system.md). References resolve to the stored preview
 * generated by the native SVG canvas editor, while missing or unauthorized
 * diagrams fall back to a safe placeholder.
 *
 * A 401 (guest mode — these routes require auth) resolves to the same
 * "not-found" state as a genuinely missing id; there's no meaningful
 * difference to show the reader in either case.
 */
export function DiagramPlaceholder({ node }: { node: MmdBlockNode }) {
  const { mode, assetRegistry, resolvedAssets } = useMmdRenderContext();
  const [state, setState] = useState<ResolveState>("loading");
  const [title, setTitle] = useState<string | null>(null);
  const diagramId = node.attrs.id;
  const [imageUrl, setImageUrl] = useState("");
  const resolved = resolvedAssets?.[`diagram://${diagramId}`];

  useEffect(() => {
    if (resolved !== undefined) { setState(resolved ? "found" : "not-found"); setImageUrl(resolved ?? ""); return; }
    setState("loading");
    const controller = new AbortController();
    const finishAsset = assetRegistry?.begin(`diagram:${diagramId}`);
    if (!diagramId) {
      setState("not-found");
      finishAsset?.();
      return;
    }
    fetch(`/api/diagrams/${encodeURIComponent(diagramId)}`, { signal: controller.signal })
      .then((res) => (res.ok ? res.json() : null))
      .then((body) => {
        const parsed = diagramDataSchema.safeParse(body?.diagram?.data);
        if (body?.diagram && parsed.success) {
          setImageUrl(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(diagramToSvg(parsed.data, body.images ?? {}))}`);
          setTitle(body.diagram.title as string);
          setState("found");
        } else {
          setState("not-found");
        }
        finishAsset?.();
      })
      .catch(() => {
        if (!controller.signal.aborted) setState("not-found");
        finishAsset?.();
      });
    return () => {
      controller.abort();
      finishAsset?.();
    };
  }, [assetRegistry, diagramId, resolved]);

  if (state === "loading") {
    return (
      <div data-mmd-asset-state="loading" className="my-4 flex items-center justify-center gap-2 rounded-lg border border-line bg-ink/[0.02] p-8 text-sm text-ink-faint">
        <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
        Loading diagram…
      </div>
    );
  }

  if (state === "found") {
    return (
      <figure data-mmd-asset-state="ready" className="my-4 overflow-hidden rounded-lg border border-line">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={imageUrl} alt={title ?? "Diagram"} loading={mode === "export" ? "eager" : "lazy"} decoding={mode === "export" ? "sync" : "async"} className="w-full" />
        <figcaption className="border-t border-line bg-surface px-3 py-2 text-center text-xs text-ink-soft">
          {node.attrs.caption || title}
        </figcaption>
      </figure>
    );
  }

  return (
    <figure data-mmd-asset-state="error" className="my-4 flex flex-col items-center rounded-lg border border-dashed border-line bg-ink/[0.02] p-8 text-center">
      <Workflow className="h-6 w-6 text-ink-faint" aria-hidden="true" />
      <p className="mt-2 text-sm text-ink-soft">Diagram not found.</p>
      <p className="mt-0.5 font-mono text-xs text-ink-faint">id: {diagramId}</p>
      {node.attrs.caption && (
        <figcaption className="mt-1 text-xs text-ink-faint">{node.attrs.caption}</figcaption>
      )}
    </figure>
  );
}
