import { describe,it,expect } from "vitest";
import { diagramDataSchema,diagramDataV2Schema,emptyDiagramV2,upgradeDiagram,emptyDiagramData } from "@/lib/diagrams/schema";
import { SHAPES } from "@/lib/diagrams/shapes";
import { ICONS } from "@/lib/diagrams/icons";
import { shapePrimitives,ports,perimeter,center,wrapText } from "@/lib/diagrams/geometry";
import { connect,reconnect,newNode,removeItems,groupNodes,ungroupNodes,moveNodes,adoptContainers,arrangeSelection,snapGuides,zOrder,copySelection,pasteSelection } from "@/lib/diagrams/editing";
import { routeEdge } from "@/lib/diagrams/routing";
import { initialHistory,commitHistory,undoHistory,redoHistory } from "@/lib/diagrams/history";
import { layoutDiagram,createTemplate,TEMPLATES } from "@/lib/diagrams/layout";
import { diagramToSvg } from "@/lib/diagrams/svg";
import { safeImageUri,MAX_PREVIEW_CHARS } from "@/lib/diagrams/svg-v2";
const pair=()=>({...emptyDiagramV2(),nodes:[newNode("rectangle",{x:20,y:20},"a"),newNode("diamond",{x:400,y:300},"b")]});
describe("diagram v2 compatibility and validation",()=>{
  it("upgrades v1 without mutating it and retains directional semantics",()=>{const legacy={...emptyDiagramData(),nodes:[{id:"a",shape:"rectangle" as const,x:0,y:0,width:100,height:60},{id:"b",shape:"circle" as const,x:200,y:0,width:100,height:60}],edges:[{id:"edge",source:"a",target:"b",directional:false}]};const before=JSON.stringify(legacy),next=upgradeDiagram(legacy);expect(JSON.stringify(legacy)).toBe(before);expect(next.version).toBe(2);expect(next.nodes[0].legacy).toBe(true);expect(next.edges[0].targetMarker).toBe("none");expect(diagramDataSchema.parse(next)).toEqual(next);});
  it("round-trips all templates",()=>{for(const name of TEMPLATES)expect(diagramDataV2Schema.safeParse(JSON.parse(JSON.stringify(createTemplate(name)))).success,name).toBe(true);});
  it("rejects nonfinite geometry, unknown properties, unsafe URLs, cycles and duplicate edge IDs",()=>{const data=pair();expect(diagramDataV2Schema.safeParse({...data,nodes:[{...data.nodes[0],x:Infinity}]}).success).toBe(false);expect(diagramDataV2Schema.safeParse({...data,html:"<script>"}).success).toBe(false);expect(diagramDataV2Schema.safeParse({...data,nodes:[{...data.nodes[0],kind:"image",imageRef:"https://evil.test/x"}]}).success).toBe(false);expect(diagramDataV2Schema.safeParse({...data,nodes:[{...data.nodes[0],kind:"container",parentId:"a"}]}).success).toBe(false);const linked=connect(data,{nodeId:"a"},{nodeId:"b"});expect(diagramDataV2Schema.safeParse({...linked,edges:[...linked.edges,...linked.edges]}).success).toBe(false);});
  it("enforces the raised node and edge limits",()=>{const data={...emptyDiagramV2(),nodes:Array.from({length:1000},(_,i)=>newNode("rectangle",{x:i*5,y:0},`n${i}`))};expect(diagramDataV2Schema.safeParse(data).success).toBe(true);expect(diagramDataV2Schema.safeParse({...data,nodes:[...data.nodes,newNode("circle",{x:0,y:0})]}).success).toBe(false);const edge=connect(data,{nodeId:"n0"},{nodeId:"n1"}).edges[0];expect(diagramDataV2Schema.safeParse({...data,edges:Array.from({length:2001},(_,i)=>({...edge,id:`e${i}`}))}).success).toBe(false);});
});
describe("shared geometry and routing",()=>{
  it.each(SHAPES)("renders finite %s geometry and ports",shape=>{const node=newNode(shape,{x:0,y:0});const primitives=shapePrimitives(node);expect(JSON.stringify(primitives)).not.toMatch(/NaN|Infinity|undefined/);for(const port of ports(node)){expect(port.x).toBeGreaterThanOrEqual(-.001);expect(port.x).toBeLessThanOrEqual(node.width+.001);expect(port.y).toBeGreaterThanOrEqual(-.001);expect(port.y).toBeLessThanOrEqual(node.height+.001);}const hit=perimeter(node,{x:900,y:50});expect(Number.isFinite(hit.x+hit.y)).toBe(true);expect(diagramToSvg({...emptyDiagramV2(),nodes:[node]})).toContain('<svg');});
  it("contains at least sixty static icons",()=>expect(Object.keys(ICONS).length).toBeGreaterThanOrEqual(60));
  it.each(["straight","orthogonal","curved"] as const)("routes %s between ports and handles free ends",routing=>{let data=connect(pair(),{nodeId:"a",portId:"right"},{nodeId:"b",portId:"left"});data={...data,edges:data.edges.map(e=>({...e,routing}))};const route=routeEdge(data.edges[0],data);expect(route.a).toMatchObject({x:200,y:70});expect(route.path).not.toMatch(/NaN|Infinity/);data=reconnect(data,data.edges[0].id,"target",{x:800,y:30});expect(routeEdge(data.edges[0],data).b).toEqual({x:800,y:30});});
  it("routes self-loops outside their node",()=>{const data=connect(pair(),{nodeId:"a"},{nodeId:"a"});expect(routeEdge(data.edges[0],data).points.length).toBeGreaterThan(3);});
  it("wraps long words, CJK and emoji without losing content",()=>{for(const text of ["a".repeat(300),"中文🙂".repeat(30)]){const lines=wrapText(text,100,16);expect(lines.join("")).toBe(text);expect(lines.every(line=>[...line].length<=10)).toBe(true);}});
  it("uses self-contained safe raster images and an explicit paper",()=>{expect(safeImageUri("https://evil.test/a.png")).toBeUndefined();expect(safeImageUri("data:image/svg+xml;base64,AAAA")).toBeUndefined();expect(safeImageUri("data:image/png;base64,"+"a".repeat(MAX_PREVIEW_CHARS))).toBeUndefined();const svg=diagramToSvg(pair());expect(svg).toContain('fill="#f7f7ef"');expect(svg).not.toMatch(/foreignObject|href="https?:/);});
});
describe("diagram editing",()=>{
  it("cleans orphan edges on deletion",()=>{const data=connect(pair(),{nodeId:"a"},{nodeId:"b"});expect(removeItems(data,["a"]).edges).toEqual([]);});
  it("groups, moves descendants and ungroups",()=>{const grouped=groupNodes(pair(),["a","b"]),group=grouped.nodes.find(n=>n.kind==="container")!;const moved=moveNodes(grouped,[group.id],100,40);expect(moved.nodes.find(n=>n.id==="a")!.x).toBe(120);const result=ungroupNodes(moved,[group.id]);expect(result.nodes).toHaveLength(2);expect(result.nodes.every(n=>!n.parentId)).toBe(true);});
  it("adopts a dropped object into a container without cycles",()=>{const data=pair(),container={...newNode("frame",{x:0,y:0},"frame"),width:1000,height:800};data.nodes[0].y=80;const result=adoptContainers({...data,nodes:[container,...data.nodes]},["a"]);expect(result.nodes.find(n=>n.id==="a")!.parentId).toBe("frame");expect(diagramDataV2Schema.safeParse(result).success).toBe(true);});
  it("aligns and sizes selections and detects guides",()=>{const data=pair();expect(arrangeSelection(data,["a","b"],"left").nodes[1].x).toBe(20);expect(arrangeSelection(data,["a","b"],"same-size").nodes[1].height).toBe(data.nodes[0].height);const snap=snapGuides(data,["a"],377,0);expect(snap.guides.some(g=>g.axis==="x")).toBe(true);expect(snap.dx).toBe(380);});
  it("changes z order deterministically",()=>{const data=pair();expect(zOrder(data,["a"],"front").nodes[0].z).toBe(1);expect(zOrder(data,["b"],"back").nodes[1].z).toBe(0);});
  it("remaps clipboard ids, parents and edges; rejects hostile JSON",()=>{const data=connect(pair(),{nodeId:"a"},{nodeId:"b"}),grouped=groupNodes(data,["a","b"]);const pasted=pasteSelection(data,copySelection(grouped,grouped.nodes.map(n=>n.id)));expect(pasted.data.nodes).toHaveLength(5);expect(pasted.data.edges).toHaveLength(2);expect(new Set(pasted.data.nodes.map(n=>n.id)).size).toBe(5);expect(()=>pasteSelection(data,'{"__proto__":{"polluted":true}}')).toThrow();expect(()=>pasteSelection(data,"x".repeat(2_000_001))).toThrow();});
  it("batches a completed gesture into one history step and holds 200 steps",()=>{let h=initialHistory(0);h=commitHistory(h,10);expect(undoHistory(h).present).toBe(0);expect(redoHistory(undoHistory(h)).present).toBe(10);for(let i=11;i<300;i++)h=commitHistory(h,i);expect(h.past).toHaveLength(200);});
  it.each(["right","down","tree","radial"] as const)("lays out %s without dropping or overlapping nodes",mode=>{const data=createTemplate("Flowchart"),next=layoutDiagram(data,mode);expect(next.edges).toEqual(data.edges);expect(next.nodes.map(n=>n.id)).toEqual(data.nodes.map(n=>n.id));for(let i=0;i<next.nodes.length;i++)for(let j=i+1;j<next.nodes.length;j++){const a=next.nodes[i],b=next.nodes[j];expect(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y).toBe(true);}expect(center(next.nodes[0]).x).toBeGreaterThan(0);});
});
