import type { DiagramDataV2,NodeV2,EdgeV2,Endpoint } from "@/lib/diagrams/schema";
import { MARKERS } from "@/lib/diagrams/schema";
import { SHAPE_REGISTRY } from "@/lib/diagrams/shapes";
export const control="min-h-11 w-full min-w-0 rounded-control border border-line bg-surface px-2 text-base text-ink";
const PRESETS={"Memoria Sage":["#e9efd0","#2b4837","#22312b"],Ink:["#ffffff","#22312b","#22312b"],Pastel:["#f5def0","#876279","#342132"],Blueprint:["#e2eef9","#305984","#203a55"],Monochrome:["#eeeeee","#333333","#111111"]};
export function Inspector({data,selection,change,arrange,copyStyle,pasteStyle}:{data:DiagramDataV2;selection:string[];change:(data:DiagramDataV2)=>void;arrange:(name:string)=>void;copyStyle:()=>void;pasteStyle:()=>void}){
  const node=data.nodes.find(n=>selection.includes(n.id)),edge=data.edges.find(e=>selection.includes(e.id));
  const patch=(value:Partial<NodeV2>)=>change({...data,nodes:data.nodes.map(n=>selection.includes(n.id)?{...n,...value,legacy:false}:n)});
  const style=(value:NonNullable<NodeV2["style"]>)=>change({...data,nodes:data.nodes.map(n=>selection.includes(n.id)?{...n,legacy:false,style:{...n.style,...value}}:n)});
  const edgePatch=(value:Partial<EdgeV2>)=>change({...data,edges:data.edges.map(e=>selection.includes(e.id)?{...e,...value,legacy:false}:e)});
  return <div className="space-y-3 p-3 text-xs text-ink-soft"><h2 className="font-display text-xl text-ink">{selection.length>1?`${selection.length} selected`:node?"Object":edge?"Connection":"Canvas"}</h2>
    {!node&&!edge&&<><p>Select an object to edit it. Drag a port to create a connection, or press C after selecting a shape.</p><label className="block">Paper color<input type="color" className={control} value={data.paper} onChange={e=>change({...data,paper:e.target.value})}/></label></>}
    {node&&<>
      <label className="block">Label<textarea className={`${control} min-h-24 py-2`} value={node.label??""} onChange={e=>patch({label:e.target.value})} maxLength={4000}/></label>
      <label className="block">Shape<select className={control} value={node.shape} onChange={e=>patch({shape:e.target.value as NodeV2["shape"]})}>{Object.values(SHAPE_REGISTRY).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
      {node.compartments?.map((value,i)=><label key={i} className="block">Class compartment {i+1}<textarea className={control} value={value} onChange={e=>patch({compartments:node.compartments!.map((v,j)=>i===j?e.target.value:v)})} maxLength={1000}/></label>)}
      <div className="grid grid-cols-2 gap-2">{(["x","y","width","height","rotation"] as const).map(key=><label key={key} className="capitalize">{key}<input className={control} type="number" value={node[key]} onChange={e=>{const value=e.target.valueAsNumber;if(Number.isFinite(value)&&Math.abs(value)<=10000&&(!["width","height"].includes(key)||value>=30)&& (key!=="rotation"||Math.abs(value)<=360))patch({[key]:value});}}/></label>)}</div>
      <label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={node.locked} onChange={e=>patch({locked:e.target.checked})}/>Lock position</label>
      <details open><summary className="min-h-11 cursor-pointer py-3 font-semibold">Appearance</summary>
        <label className="block">Palette<select className={control} defaultValue="" onChange={e=>{const values=PRESETS[e.target.value as keyof typeof PRESETS];if(values)style({fill:values[0],stroke:values[1],textColor:values[2]});}}><option value="">Choose palette</option>{Object.keys(PRESETS).map(name=><option key={name}>{name}</option>)}</select></label>
        <div className="grid grid-cols-3 gap-2">{(["fill","stroke","textColor"] as const).map(key=><label key={key}>{key}<input type="color" className={control} value={node.style?.[key]?.slice(0,7)??"#22312b"} onChange={e=>style({[key]:e.target.value})}/></label>)}</div>
        <div className="grid grid-cols-2 gap-2">{(["strokeWidth","radius","opacity","padding"] as const).map(key=><label key={key}>{key}<input className={control} type="number" min={0} max={key==="opacity"?1:key==="strokeWidth"?20:100} step={key==="opacity"?.1:1} value={node.style?.[key]??(key==="opacity"?1:key==="strokeWidth"?2:12)} onChange={e=>{const value=e.target.valueAsNumber;if(Number.isFinite(value)&&value>=0&&value<=(key==="opacity"?1:key==="strokeWidth"?20:100))style({[key]:value});}}/></label>)}</div>
        <label className="block">Border<select className={control} value={node.style?.dash??"solid"} onChange={e=>style({dash:e.target.value as "solid"})}>{["solid","dashed","dotted"].map(value=><option key={value}>{value}</option>)}</select></label>
        <label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={node.style?.shadow??false} onChange={e=>style({shadow:e.target.checked})}/>Shadow</label>
        {(["gradient","highlight"] as const).map(key=><div key={key}><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={Boolean(node.style?.[key])} onChange={e=>style({[key]:e.target.checked?"#e9efd0":undefined})}/>{key}</label>{node.style?.[key]&&<input aria-label={`${key} color`} type="color" className={control} value={node.style[key]} onChange={e=>style({[key]:e.target.value})}/>}</div>)}
      </details>
      <details><summary className="min-h-11 cursor-pointer py-3 font-semibold">Typography</summary>
        <label className="block">Font<select className={control} value={node.style?.fontFamily??"sans"} onChange={e=>style({fontFamily:e.target.value as "sans"})}>{["sans","serif","mono","handwriting"].map(value=><option key={value}>{value}</option>)}</select></label>
        <label className="block">Size<input className={control} type="number" min={8} max={72} value={node.style?.fontSize??16} onChange={e=>{const n=e.target.valueAsNumber;if(n>=8&&n<=72)style({fontSize:n});}}/></label>
        <label className="block">Line height<input className={control} type="number" min={1} max={3} step={.1} value={node.style?.lineHeight??1.3} onChange={e=>{const n=e.target.valueAsNumber;if(n>=1&&n<=3)style({lineHeight:n});}}/></label>
        <div className="grid grid-cols-2">{(["bold","italic","underline","strike"] as const).map(key=><label className="flex min-h-11 items-center gap-2" key={key}><input type="checkbox" checked={node.style?.[key]??false} onChange={e=>style({[key]:e.target.checked})}/>{key}</label>)}</div>
        <label className="block">Horizontal<select className={control} value={node.style?.textAlign??"center"} onChange={e=>style({textAlign:e.target.value as "center"})}>{["left","center","right"].map(value=><option key={value}>{value}</option>)}</select></label>
        <label className="block">Vertical<select className={control} value={node.style?.verticalAlign??"middle"} onChange={e=>style({verticalAlign:e.target.value as "middle"})}>{["top","middle","bottom"].map(value=><option key={value}>{value}</option>)}</select></label>
      </details>
      <details><summary className="min-h-11 cursor-pointer py-3 font-semibold">Arrange</summary><div className="grid grid-cols-2">{["left","center","right","top","middle","bottom","distribute-x","distribute-y","same-size","front","back","forward","backward","Group","Ungroup","Select same type"].map(name=><button type="button" key={name} className="min-h-11 px-1 text-left" onClick={()=>arrange(name)}>{name.replaceAll("-"," ")}</button>)}</div></details>
      <div className="flex"><button type="button" className="min-h-11 px-2" onClick={copyStyle}>Copy style</button><button type="button" className="min-h-11 px-2" onClick={pasteStyle}>Paste style</button></div>
    </>}
    {edge&&<>
      <label className="block">Label<input className={control} value={edge.label??""} maxLength={500} onChange={e=>edgePatch({label:e.target.value})}/></label>
      <label className="block">Routing<select className={control} value={edge.routing} onChange={e=>edgePatch({routing:e.target.value as "straight"})}>{["straight","orthogonal","curved"].map(value=><option key={value}>{value}</option>)}</select></label>
      {(["source","target"] as const).map(end=><div key={end}><label className="block capitalize">{end}<select className={control} value={"nodeId" in edge[end]?(edge[end] as {nodeId:string}).nodeId:"free"} onChange={e=>edgePatch({[end]:e.target.value==="free"?{x:0,y:0}:{nodeId:e.target.value}})}><option value="free">Free point</option>{data.nodes.map(n=><option key={n.id} value={n.id}>{n.label||n.shape}</option>)}</select></label>{"x" in edge[end]&&<div className="grid grid-cols-2 gap-2">{(["x","y"] as const).map(axis=><label key={axis}>{end} {axis}<input className={control} type="number" value={(edge[end] as {x:number;y:number})[axis]} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))edgePatch({[end]:{...edge[end],[axis]:n} as Endpoint});}}/></label>)}</div>}<label className="block">{end} marker<select className={control} value={edge[`${end}Marker`]} onChange={e=>edgePatch({[`${end}Marker`]:e.target.value})}>{MARKERS.map(value=><option key={value}>{value}</option>)}</select></label></div>)}
      <label className="block">Color<input type="color" className={control} value={edge.color} onChange={e=>edgePatch({color:e.target.value})}/></label>
      <label className="block">Width<input type="number" className={control} min={.5} max={20} step={.5} value={edge.width} onChange={e=>{const n=e.target.valueAsNumber;if(n>=.5&&n<=20)edgePatch({width:n});}}/></label>
      <label className="block">Line<select className={control} value={edge.dash} onChange={e=>edgePatch({dash:e.target.value as "solid"})}>{["solid","dashed","dotted"].map(value=><option key={value}>{value}</option>)}</select></label>
      <label className="block">Label position<input type="range" className="min-h-11 w-full" min={0} max={1} step={.01} value={edge.labelPosition} onChange={e=>edgePatch({labelPosition:e.target.valueAsNumber})}/></label>
      <label className="block">Label size<input type="number" className={control} min={8} max={72} value={edge.labelStyle?.fontSize??12} onChange={e=>{const n=e.target.valueAsNumber;if(n>=8&&n<=72)edgePatch({labelStyle:{...edge.labelStyle,fontSize:n}});}}/></label>
      <button type="button" className="min-h-11 px-2" onClick={()=>edgePatch({waypoints:[...edge.waypoints,{x:100,y:100}]})}>Add bend</button>
      {edge.waypoints.map((p,i)=><div key={i} className="grid grid-cols-2 gap-2">{(["x","y"] as const).map(axis=><label key={axis}>Bend {i+1} {axis}<input className={control} type="number" value={p[axis]} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))edgePatch({waypoints:edge.waypoints.map((v,j)=>i===j?{...v,[axis]:n}:v)});}}/></label>)}<button type="button" className="min-h-11 text-danger" onClick={()=>edgePatch({waypoints:edge.waypoints.filter((_,j)=>i!==j)})}>Remove bend</button></div>)}
    </>}
  </div>;
}
