import { Undo2,Redo2,Save } from "lucide-react";
import { Button } from "@/components/ui/button";
export function Toolbar({title,setTitle,dirty,busy,save,onInsert,undo,redo,canUndo,canRedo,panel,setPanel,tool,setTool,grid,setGrid,fit,zoom,exportFile,copyEmbed,layout}:{title:string;setTitle:(title:string)=>void;dirty:boolean;busy:boolean;save:(insert?:boolean)=>void;onInsert:boolean;undo:()=>void;redo:()=>void;canUndo:boolean;canRedo:boolean;panel:string|null;setPanel:(panel:string|null)=>void;tool:string;setTool:(tool:"select"|"pan"|"text"|"connect")=>void;grid:boolean;setGrid:(grid:boolean)=>void;fit:()=>void;zoom:(factor:number)=>void;exportFile:(format:"svg"|"png")=>void;copyEmbed:()=>void;layout:(mode:"right"|"down"|"tree"|"radial")=>void}){
  return <header className="flex flex-wrap items-center gap-2 rounded-card border border-line bg-surface p-2">
    <div className="min-w-0 flex-1 basis-40"><input aria-label="Diagram title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} className="min-h-11 w-full min-w-0 rounded-control bg-transparent px-2 font-display text-lg text-ink"/><p className="px-2 text-xs text-ink-faint">{busy?"Working…":dirty?"Unsaved changes":"Saved"}</p></div>
    <Button variant="ghost" aria-label="Undo" disabled={!canUndo||busy} onClick={undo} className="min-h-11 min-w-11"><Undo2 className="h-4 w-4"/></Button><Button variant="ghost" aria-label="Redo" disabled={!canRedo||busy} onClick={redo} className="min-h-11 min-w-11"><Redo2 className="h-4 w-4"/></Button>
    <Button disabled={busy} onClick={()=>save(false)} className="min-h-11"><Save className="h-4 w-4"/>Save</Button>{onInsert&&<Button variant="outline" disabled={busy} onClick={()=>save(true)} className="min-h-11">Save &amp; insert into memory</Button>}
    <div className="flex w-full flex-wrap items-center gap-1 border-t border-line pt-2">
      {["Library","My diagrams","Inspector","Templates","Shortcuts"].map(name=><button type="button" key={name} aria-expanded={panel===name} className={`min-h-11 rounded-control px-3 text-xs ${panel===name?"bg-accent-soft text-accent-dark":"text-ink-soft hover:bg-surface-muted"}`} onClick={()=>setPanel(panel===name?null:name)}>{name}</button>)}
      <span className="mx-1 h-5 w-px bg-line" aria-hidden="true"/>
      {(["select","pan","text","connect"] as const).map(name=><button type="button" key={name} aria-pressed={tool===name} className={`min-h-11 rounded-control px-2 text-xs capitalize ${tool===name?"bg-accent-soft text-accent-dark":"text-ink-soft"}`} onClick={()=>setTool(name)}>{name}</button>)}
      <label className="flex min-h-11 items-center gap-2 px-2 text-xs text-ink-soft"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>Grid snap</label>
      <button type="button" className="min-h-11 px-2 text-xs text-ink-soft" onClick={fit}>Fit</button><button type="button" className="min-h-11 px-2 text-xs text-ink-soft" onClick={()=>zoom(1.2)}>−</button><button type="button" className="min-h-11 px-2 text-xs text-ink-soft" onClick={()=>zoom(1/1.2)}>+</button>
      <details className="relative"><summary className="min-h-11 cursor-pointer px-3 py-3 text-xs text-ink-soft">Arrange</summary><div className="absolute left-0 top-full z-40 grid w-40 rounded-control border border-line bg-surface p-1 shadow-card">{(["right","down","tree","radial"] as const).map(mode=><button key={mode} type="button" className="min-h-11 px-2 text-left text-xs capitalize text-ink" onClick={()=>layout(mode)}>{mode==="right"?"Arrange →":mode==="down"?"Arrange ↓":mode}</button>)}</div></details>
      <details className="relative"><summary className="min-h-11 cursor-pointer px-3 py-3 text-xs text-ink-soft">Export</summary><div className="absolute right-0 top-full z-40 grid w-40 rounded-control border border-line bg-surface p-1 shadow-card"><button type="button" className="min-h-11 px-2 text-left text-xs" onClick={()=>exportFile("svg")}>Download SVG</button><button type="button" className="min-h-11 px-2 text-left text-xs" onClick={()=>exportFile("png")}>Download PNG</button><button type="button" className="min-h-11 px-2 text-left text-xs" onClick={copyEmbed}>Copy embed</button></div></details>
    </div>
  </header>;
}
