"use client";
import { useEffect,useRef,useState } from "react";
import { diagramDataSchema,diagramDataV2Schema,emptyDiagramV2,upgradeDiagram,type DiagramDataV2,type NodeV2,type Point } from "@/lib/diagrams/schema";
import { SHAPE_REGISTRY,type ShapeId } from "@/lib/diagrams/shapes";
import { diagramToSvg,getDiagramBounds,type DiagramBounds } from "@/lib/diagrams/svg";
import { MAX_PREVIEW_CHARS,type DiagramImages } from "@/lib/diagrams/svg-v2";
import { initialHistory,commitHistory,undoHistory,redoHistory } from "@/lib/diagrams/history";
import { newNode,removeItems,moveNodes,copySelection,pasteSelection,groupNodes,ungroupNodes,arrangeSelection,zOrder,type Arrangement } from "@/lib/diagrams/editing";
import { createTemplate,layoutDiagram } from "@/lib/diagrams/layout";
import { Canvas } from "./canvas";
import { Toolbar } from "./toolbar";
import { Palette } from "./palette";
import { Inspector } from "./inspector";
import { MyDiagrams,type DiagramSummary } from "./my-diagrams";
import { TemplateGallery } from "./template-gallery";

const signature=(title:string,data:DiagramDataV2)=>JSON.stringify([title,data]);
export function DiagramEditor({initialDiagrams,initialDiagramId,onInsert,onDirtyChange}:{initialDiagrams:DiagramSummary[];initialDiagramId?:string;onInsert?:(id:string)=>void;onDirtyChange?:(dirty:boolean)=>void}){
  const initial=initialDiagrams.find(d=>d.id===initialDiagramId)??initialDiagrams[0];
  const [diagrams,setDiagrams]=useState(initialDiagrams),[id,setId]=useState<string|null>(null),[title,setTitle]=useState(initial?.title??"Untitled diagram");
  const [history,setHistory]=useState(()=>initialHistory(emptyDiagramV2()));const data=history.present;
  const [saved,setSaved]=useState(()=>signature(initial?.title??"Untitled diagram",emptyDiagramV2()));
  const [selection,select]=useState<string[]>([]),[camera,setCamera]=useState<DiagramBounds>({x:0,y:0,width:1000,height:650});
  const [images,setImages]=useState<DiagramImages>({}),[tool,setTool]=useState<"select"|"pan"|"text"|"connect">("select"),[panel,setPanel]=useState<string|null>(initial?null:"Templates"),[grid,setGrid]=useState(true);
  const [snapConnectEnabled,setSnapConnectEnabled]=useState(false);
  const [loading,setLoading]=useState(Boolean(initial)),[saving,setSaving]=useState(false),[loadFailed,setLoadFailed]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
  const request=useRef<AbortController|null>(null),styleClipboard=useRef<NodeV2["style"]>(),clipboard=useRef("");
  const dirty=signature(title,data)!==saved,busy=loading||saving||loadFailed;
  useEffect(()=>{if(initial)void load(initial.id);return()=>request.current?.abort();/* Initial document only. */
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);
  useEffect(()=>onDirtyChange?.(dirty),[dirty,onDirtyChange]);
  useEffect(()=>{if(!dirty)return;const protect=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue="";};window.addEventListener("beforeunload",protect);return()=>window.removeEventListener("beforeunload",protect);},[dirty]);
  function change(next:DiagramDataV2){const result=diagramDataV2Schema.safeParse(next);if(!result.success){setError(result.error.issues[0]?.message??"This change is outside the diagram limits.");return;}setHistory(h=>commitHistory(h,next));setMessage("");}
  function fit(next=data){setCamera(getDiagramBounds(next));}
  function zoom(factor:number){setCamera(c=>{const width=Math.max(250,Math.min(10000,c.width*factor)),height=width*c.height/c.width;return{x:c.x+(c.width-width)/2,y:c.y+(c.height-height)/2,width,height};});}
  const discard=()=>!dirty||window.confirm("Discard unsaved changes to this diagram?");
  function fresh(){if(!discard())return;request.current?.abort();const next=emptyDiagramV2();setId(null);setTitle("Untitled diagram");setHistory(initialHistory(next));setSaved(signature("Untitled diagram",next));select([]);setImages({});setError("");setLoadFailed(false);setLoading(false);setPanel("Templates");fit(next);}
  async function load(nextId:string){request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError("");setLoadFailed(false);
    try{const response=await fetch(`/api/diagrams/${encodeURIComponent(nextId)}`,{signal:controller.signal});const body=await response.json();if(!response.ok||!body.diagram||body.diagram.loadError)throw Error(body.error??"This diagram could not be loaded safely. Retry opening it.");const next=upgradeDiagram(diagramDataSchema.parse(body.diagram.data));if(controller.signal.aborted)return;setId(body.diagram.id);setTitle(body.diagram.title);setHistory(initialHistory(next));setSaved(signature(body.diagram.title,next));setImages(body.images??{});select([]);fit(next);setPanel(null);}
    catch(reason){if(!controller.signal.aborted){setLoadFailed(true);setError(reason instanceof Error?reason.message:"Could not open this diagram.");}}finally{if(!controller.signal.aborted)setLoading(false);}}
  async function save(insert=false){if(busy)return;setSaving(true);setError("");try{
    const response=await fetch(id?`/api/diagrams/${id}`:"/api/diagrams",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:title.trim()||"Untitled diagram",data})});const result=await response.json();if(!response.ok||!result.diagram)throw Error(result.error??"Could not save. Try again.");const diagram=result.diagram,next=upgradeDiagram(diagramDataSchema.parse(diagram.data));setId(diagram.id);setTitle(diagram.title);setHistory(h=>({...h,present:next}));setSaved(signature(diagram.title,next));setDiagrams(items=>[{id:diagram.id,title:diagram.title,updatedAt:diagram.updatedAt},...items.filter(d=>d.id!==diagram.id)]);
    const loaded=await fetch(`/api/diagrams/${diagram.id}`);if(!loaded.ok)throw Error("Diagram saved, but preview assets could not be loaded. Retry saving to refresh its preview.");const body=await loaded.json();const assets=body.images??{};setImages(assets);
    const dataUrl=`data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(diagramToSvg(next,assets))))}`;if(dataUrl.length>MAX_PREVIEW_CHARS)throw Error("Diagram saved, but its preview is too large. Reduce the image count and save again.");
    const preview=await fetch(`/api/diagrams/${diagram.id}/preview`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dataUrl})});if(!preview.ok)throw Error("Diagram saved, but preview upload failed. Retry saving.");setMessage("All changes saved");if(insert)onInsert?.(diagram.id);
  }catch(reason){setError(reason instanceof Error?reason.message:"Could not save this diagram.");}finally{setSaving(false);}}
  function add(shape:string,point?:Point){if(shape==="image"){setPanel("Library");setMessage("Use Upload image in the library.");return;}const icon=shape.startsWith("icon:")?shape.slice(5):undefined;const key=icon?"icon":shape;if(!Object.hasOwn(SHAPE_REGISTRY,key))return;const node={...newNode(key as ShapeId,point??{x:camera.x+camera.width/2-90,y:camera.y+camera.height/2-50}),z:data.nodes.length,...(icon?{iconId:icon}:{})};change({...data,nodes:[...data.nodes,node]});select([node.id]);setTool("select");}
  async function upload(file:File){if(file.size>5*1024*1024){setError("Images must be 5 MB or smaller.");return;}setSaving(true);try{const form=new FormData();form.set("file",file);const response=await fetch("/api/media",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw Error(result.error??"Image upload failed.");const image=await createImageBitmap(file);const canvas=document.createElement("canvas");const scale=Math.min(1,1024/image.width,1024/image.height);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")!.drawImage(image,0,0,canvas.width,canvas.height);image.close();const uri=canvas.toDataURL("image/webp",.8);setImages(items=>({...items,[result.src]:uri}));const node={...newNode("image",{x:camera.x+100,y:camera.y+100}),imageRef:result.src,width:Math.min(400,canvas.width),height:Math.min(400,canvas.width)*canvas.height/canvas.width};change({...data,nodes:[...data.nodes,node]});select([node.id]);setMessage("Image added. Save to update embeds.");}catch(reason){setError(reason instanceof Error?reason.message:"Image upload failed.");}finally{setSaving(false);}}
  async function exportFile(format:"svg"|"png"){try{const svg=diagramToSvg(data,images);let blob=new Blob([svg],{type:"image/svg+xml"});if(format==="png"){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();const bounds=getDiagramBounds(data),ratio=Math.min(2,4096/Math.max(bounds.width,bounds.height));const canvas=document.createElement("canvas");canvas.width=Math.ceil(bounds.width*ratio);canvas.height=Math.ceil(bounds.height*ratio);canvas.getContext("2d")!.drawImage(image,0,0,canvas.width,canvas.height);blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(Error("PNG creation failed.")),"image/png"));}finally{URL.revokeObjectURL(url);}}const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${title.replace(/[^\p{L}\p{N} _-]/gu,"")||"diagram"}.${format}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(reason){setError(reason instanceof Error?reason.message:"Export failed.");}}
  async function copyEmbed(){if(!id||dirty){setMessage("Save this diagram before copying its embed.");return;}try{await navigator.clipboard.writeText(`:::diagram{id="${id}"}\n:::`);setMessage("Diagram embed copied");}catch{setError("Clipboard unavailable. Use the Diagram button in your memory editor.");}}
  function arrange(name:string){if(["Group","Ungroup","Select same type"].includes(name)){act(name);return;}if(["front","back","forward","backward"].includes(name))change(zOrder(data,selection,name as "front"));else change(arrangeSelection(data,selection,name as Arrangement));}
  function act(action:string){if(busy)return;try{
    if(action==="Delete"){change(removeItems(data,selection));setMessage(`Deleted ${selection.length} items`);select([]);}
    else if(action==="Duplicate"){const result=pasteSelection(data,copySelection(data,selection));change(result.data);select(result.ids);}
    else if(action==="Copy"||action==="Cut"){clipboard.current=copySelection(data,selection);void navigator.clipboard.writeText(clipboard.current).catch(()=>setMessage("Copied within this workspace; system clipboard unavailable."));if(action==="Cut"){change(removeItems(data,selection));select([]);}}
    else if(action==="Paste"){void (async()=>{let value=clipboard.current;try{value=await navigator.clipboard.readText();}catch{ /* Internal clipboard remains available. */ }try{const result=pasteSelection(data,value);change(result.data);select(result.ids);}catch{setError("Clipboard does not contain a valid Memoria diagram.");}})();}
    else if(action==="Group")change(groupNodes(data,selection));else if(action==="Ungroup")change(ungroupNodes(data,selection));
    else if(action==="Bring to front")change(zOrder(data,selection,"front"));else if(action==="Send to back")change(zOrder(data,selection,"back"));
    else if(action==="Lock / unlock")change({...data,nodes:data.nodes.map(n=>selection.includes(n.id)?{...n,locked:!n.locked}:n)});
    else if(action==="Select same type"){const node=data.nodes.find(n=>selection.includes(n.id));if(node)select(data.nodes.filter(n=>n.shape===node.shape).map(n=>n.id));}
  }catch(reason){setError(reason instanceof Error?reason.message:"Could not change selection.");}}
  async function libraryAction(action:"duplicate"|"delete"|"rename",nextId:string,nextTitle?:string){if(action==="delete"&&!window.confirm("Delete this saved diagram? Notes that embed it will show Diagram not found."))return;try{const response=await fetch(`/api/diagrams/${nextId}${action==="duplicate"?"/duplicate":""}`,{method:action==="duplicate"?"POST":action==="delete"?"DELETE":"PATCH",headers:{"Content-Type":"application/json"},...(nextTitle?{body:JSON.stringify({title:nextTitle})}:{})});const result=await response.json();if(!response.ok)throw Error(result.error??"Could not update the library.");if(action==="delete"){setDiagrams(items=>items.filter(d=>d.id!==nextId));if(id===nextId){setId(null);setSaved("");}}else{const d=result.diagram;setDiagrams(items=>[{id:d.id,title:d.title,updatedAt:d.updatedAt},...items.filter(item=>item.id!==d.id)]);if(action==="rename"&&id===nextId){setTitle(d.title);setSaved(signature(d.title,data));}}}catch(reason){setError(reason instanceof Error?reason.message:"Library update failed.");}}
  function template(name:string){const next=createTemplate(name);change(next);select([]);fit(next);setPanel(null);}
  const side=panel&&panel!=="Shortcuts";
  return <section className="min-w-0 space-y-2" onKeyDown={event=>{if(busy||/INPUT|TEXTAREA|SELECT/.test((event.target as HTMLElement).tagName))return;const mod=event.ctrlKey||event.metaKey,key=event.key.toLowerCase();if(mod&&["z","y","c","v","x","d","a","g"].includes(key)){event.preventDefault();if(key==="z")setHistory(h=>event.shiftKey?redoHistory(h):undoHistory(h));else if(key==="y")setHistory(redoHistory);else if(key==="a")select(data.nodes.map(n=>n.id));else act(({c:"Copy",v:"Paste",x:"Cut",d:"Duplicate",g:event.shiftKey?"Ungroup":"Group"} as Record<string,string>)[key]);}else if(key==="delete"||key==="backspace"){event.preventDefault();act("Delete");}else if(key.startsWith("arrow")){event.preventDefault();const step=event.shiftKey?20:1;change(moveNodes(data,selection,key==="arrowleft"?-step:key==="arrowright"?step:0,key==="arrowup"?-step:key==="arrowdown"?step:0));}else if(key==="v")setTool("select");else if(key==="h")setTool("pan");else if(key==="t")setTool("text");else if(key==="["||key==="]")change(zOrder(data,selection,key==="["?"backward":"forward"));else if(key==="+"||key==="=")zoom(1/1.2);else if(key==="-")zoom(1.2);}}>
    <Toolbar title={title} setTitle={setTitle} dirty={dirty} busy={busy} save={save} onInsert={Boolean(onInsert)} undo={()=>setHistory(undoHistory)} redo={()=>setHistory(redoHistory)} canUndo={Boolean(history.past.length)} canRedo={Boolean(history.future.length)} panel={panel} setPanel={setPanel} tool={tool} setTool={setTool} grid={grid} setGrid={setGrid} fit={()=>fit()} zoom={zoom} exportFile={exportFile} copyEmbed={copyEmbed} layout={mode=>{const next=layoutDiagram(data,mode);change(next);fit(next);}}/>
    {error&&<div role="alert" className="flex flex-wrap items-center gap-2 rounded-control border border-danger/30 bg-danger/5 p-3 text-sm text-danger"><p className="min-w-0 flex-1 break-words">{error}</p>{loadFailed&&<><button type="button" className="min-h-11 underline" onClick={()=>void load(initial?.id??id??"")}>Retry opening</button><button type="button" className="min-h-11 underline" onClick={fresh}>New diagram</button></>}</div>}
    <fieldset disabled={busy} className="min-w-0 border-0 p-0"><legend className="sr-only">Diagram workspace</legend><div className="relative flex min-w-0 gap-2">
      {side&&<aside aria-label={panel!} className={`fixed inset-x-2 bottom-2 z-40 max-h-[65dvh] overflow-y-auto overscroll-contain rounded-card border border-line bg-surface shadow-card lg:static lg:z-auto lg:max-h-[60dvh] lg:w-64 lg:shrink-0 ${panel==="Inspector"?"lg:order-2":""}`}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-line bg-surface px-3"><h2 className="text-sm font-semibold text-ink">{panel}</h2><button type="button" className="min-h-11 min-w-11 text-ink" aria-label={`Close ${panel}`} onClick={()=>setPanel(null)}>×</button></div>
        {panel==="Library"&&<Palette add={add} upload={upload}/>}{panel==="Inspector"&&<Inspector data={data} selection={selection} change={change} arrange={arrange} copyStyle={()=>{styleClipboard.current=data.nodes.find(n=>selection.includes(n.id))?.style;setMessage("Style copied");}} pasteStyle={()=>change({...data,nodes:data.nodes.map(n=>selection.includes(n.id)?{...n,legacy:false,style:{...styleClipboard.current}}:n)})}/>}
        {panel==="My diagrams"&&<MyDiagrams diagrams={diagrams} open={next=>{if(discard())void load(next);}} duplicate={next=>void libraryAction("duplicate",next)} remove={next=>void libraryAction("delete",next)} rename={(next,name)=>void libraryAction("rename",next,name)} fresh={fresh}/>}{panel==="Templates"&&<TemplateGallery choose={template}/>}
      </aside>}
      <Canvas snapConnectEnabled={snapConnectEnabled} data={data} images={images} selection={selection} select={select} change={change} camera={camera} setCamera={setCamera} tool={tool} grid={grid} act={act} announce={setMessage} disabled={busy} add={add} zoom={zoom}/>
    </div></fieldset>
    <div className="flex flex-wrap items-center justify-between gap-2">    <label className="flex min-h-11 items-center gap-2 text-xs text-ink-soft"><input type="checkbox" checked={snapConnectEnabled} onChange={e=>setSnapConnectEnabled(e.target.checked)}/>Snap-connect nearby shapes</label>
    <p role="status" aria-live="polite" className=" text-xs text-ink-soft">{loading?"Opening diagram…":message}</p>
</div>
    {panel==="Shortcuts"&&<div className="rounded-card border border-line bg-surface p-4 text-sm leading-relaxed text-ink-soft">Drag to select an area. Shift-click adds to selection. Drag ports to connect; double-click a connection to add a bend. Double-click a label to edit. C starts a keyboard connection; arrows choose its target, Enter connects. Arrows move selected objects; Shift moves by 20. Ctrl/Cmd+Z / Shift+Z undo and redo. Ctrl/Cmd+C/V/X/D copy, paste, cut and duplicate. Ctrl/Cmd+G groups; Shift ungroups. V selects, H pans, T adds text. Space-drag pans. Ctrl/Cmd+wheel or pinch zooms. [ / ] changes z-order. Enter edits; Esc cancels editing.</div>}
  </section>;
}
