import Link from "next/link";
import { ArrowRight, ArrowUpRight, LineChart, RotateCcw, TrendingUp } from "lucide-react";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth/session";
import { EmptyState } from "@/components/ui/empty-state";
import { PageDescription, PageHeader, PageHeaderContent, PageShell, PageTitle } from "@/components/ui/page";
import { ButtonLink } from "@/components/ui/button";
import { formatRelativeTime } from "@/lib/utils";

export default async function ProgressPage() {
  const user = await requireUser();
  const since = new Date(); since.setUTCHours(0, 0, 0, 0); since.setUTCDate(since.getUTCDate() - 13);
  const [attempts, reviews, sessions, dueCount] = await Promise.all([
    prisma.quizAttempt.findMany({ where: { userId: user.id, status: "COMPLETED" }, orderBy: { completedAt: "desc" }, take: 40, select: { id: true, score: true, totalQuestions: true, completedAt: true, quiz: { select: { id: true, title: true } } } }),
    prisma.flashcardReview.findMany({ where: { userId: user.id, reviewedAt: { gte: since } }, orderBy: { reviewedAt: "asc" }, select: { grade: true, reviewedAt: true } }),
    prisma.studySession.findMany({ where: { userId: user.id, completedAt: { gte: since } }, orderBy: { completedAt: "desc" }, select: { id: true, reviewed: true, correct: true, completedAt: true } }),
    prisma.flashcard.count({ where: { ownerId: user.id, OR: [{ progress: { none: { userId: user.id } } }, { progress: { some: { userId: user.id, dueAt: { lte: new Date() } } } }] } }),
  ]);
  const latest = attempts.filter((attempt, index) => attempts.findIndex(other => other.quiz.id === attempt.quiz.id) === index);
  const weak = latest.filter(attempt => attempt.score < attempt.totalQuestions).sort((a,b) => a.score / Math.max(a.totalQuestions,1) - b.score / Math.max(b.totalQuestions,1));
  const changes = latest.flatMap(attempt => {
    const previous = attempts.find(item => item.quiz.id === attempt.quiz.id && item.id !== attempt.id);
    if (!previous) return [];
    return [{ attempt, previous, difference: Math.round((attempt.score / Math.max(attempt.totalQuestions,1) - previous.score / Math.max(previous.totalQuestions,1)) * 100) }];
  });
  const improving = changes.filter(item => item.difference > 0);
  const days = Array.from({ length: 14 }, (_, index) => { const date = new Date(since); date.setUTCDate(date.getUTCDate() + index); return { date, key: date.toISOString().slice(0,10), count: 0 }; });
  reviews.forEach(review => { const day = days.find(item => item.key === review.reviewedAt.toISOString().slice(0,10)); if (day) day.count++; });
  const max = Math.max(1, ...days.map(day => day.count));
  const activeDays = new Set([...reviews.map(item => item.reviewedAt.toISOString().slice(0,10)), ...attempts.filter(item => item.completedAt && item.completedAt >= since).map(item => item.completedAt!.toISOString().slice(0,10))]).size;
  return <PageShell>
    <PageHeader><PageHeaderContent><p className="eyebrow">A record of returning</p><PageTitle className="mt-3">Look how far you’ve come.</PageTitle><PageDescription>What is taking root, what needs another look, and where to go next.</PageDescription></PageHeaderContent><ButtonLink href="/study">Keep learning<ArrowRight className="h-4 w-4" /></ButtonLink></PageHeader>
    {!attempts.length && !reviews.length && !sessions.length ? <EmptyState icon={LineChart} title="Your story starts with one session." description="Practice a quiz or recall a few flashcards. Your real activity will help you see what is sticking." actionLabel="Choose a practice" actionHref="/study" /> : <>
      <section className="grid gap-8 border-y border-line py-8 md:grid-cols-[1.3fr_1fr]"><div><p className="index-label">The last two weeks</p><h2 className="mt-4 max-w-xl font-display text-3xl leading-tight tracking-tight">{activeDays > 0 ? `You made room for learning on ${activeDays} ${activeDays === 1 ? "day" : "days"}.` : "Your earlier practice is here to build on."}</h2><p className="mt-4 text-sm leading-relaxed text-ink-soft">{reviews.length > 0 ? `${reviews.filter(item => item.grade >= 3).length} of ${reviews.length} flashcard reviews felt Good or Easy.` : "Flashcard reviews will add another view of what you remember."}{sessions.length > 0 ? ` You completed ${sessions.length} ${sessions.length === 1 ? "study session" : "study sessions"}.` : ""}</p></div><div className="annotation self-center"><RotateCcw className="mb-3 h-5 w-5" /><p>{dueCount ? `${dueCount} flashcards are new or ready for another review.` : "No flashcards are due right now. Choose a new challenge or revisit a guide."}</p><Link href={dueCount ? "/study/review" : "/study"} className="journal-link mt-3">{dueCount ? "Review what’s due" : "Find your next practice"}<ArrowRight className="h-4 w-4" /></Link></div></section>
      <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_20rem]">
        <section><div className="journal-rule"><h2 className="section-heading">The rhythm of remembering</h2><span className="text-xs text-ink-faint">14 days</span></div><figure className="mt-6"><div className="flex h-44 items-end gap-1.5 sm:gap-3" role="img" aria-label={`Daily flashcard reviews over fourteen days: ${days.map(day => day.count).join(", ")}`}>{days.map(day => <div key={day.key} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="font-mono text-[10px] text-ink-soft">{day.count || ""}</span><div className="flex h-28 w-full items-end border-b border-line"><div className="w-full bg-action" style={{ height: `${day.count / max * 100}%` }} /></div><span className="font-mono text-[10px] text-ink-faint">{day.date.getUTCDate()}</span></div>)}</div><figcaption className="mt-4 text-xs text-ink-faint">Flashcard reviews by day (UTC). Returning matters more than filling every day.</figcaption></figure><details className="mt-4"><summary className="cursor-pointer py-2 text-xs text-ink-soft">View the activity as a list</summary><ul className="mt-2 grid grid-cols-2 gap-2 text-xs">{days.map(day => <li key={day.key} className="flex justify-between gap-3 border-b border-line py-2"><span>{day.date.toLocaleDateString("en", { month: "short", day: "numeric", timeZone: "UTC" })}</span><span>{day.count} reviews</span></li>)}</ul></details></section>
        <section><div className="journal-rule"><h2 className="section-heading">Taking root</h2><TrendingUp className="h-5 w-5 text-study" /></div>{improving.length ? improving.slice(0,3).map(item => <Link key={item.attempt.id} href={`/quizzes/${item.attempt.quiz.id}/results?attempt=${item.attempt.id}`} className="block border-b border-line py-5"><p className="text-xs font-medium text-study">Up {item.difference} percentage points</p><p className="mt-2 break-words font-display text-xl">{item.attempt.quiz.title}</p><p className="mt-2 text-xs text-ink-soft">Compared with your previous completed attempt.</p></Link>) : <p className="py-5 text-sm leading-relaxed text-ink-soft">{changes.length ? "Keep practicing. Your latest attempts have not improved on their previous scores yet." : "Try a quiz more than once to see how your understanding changes."}</p>}</section>
      </div>
      {weak.length > 0 && <section><div className="journal-rule"><h2 className="section-heading">An invitation to revisit</h2><span className="text-xs text-ink-faint">Latest attempt per quiz</span></div><div className="divide-y divide-line">{weak.slice(0,5).map(attempt => <Link key={attempt.id} href={`/quizzes/${attempt.quiz.id}/results?attempt=${attempt.id}&show=missed`} className="flex items-center gap-5 py-5"><span className="min-w-0 flex-1"><span className="block break-words font-display text-xl">{attempt.quiz.title}</span><span className="mt-2 block text-xs text-ink-soft">{attempt.totalQuestions - attempt.score} questions worth another look</span></span><ArrowRight className="h-4 w-4 text-accent-dark" /></Link>)}</div></section>}
      {attempts.length > 0 && <section><div className="journal-rule"><h2 className="section-heading">Pages in your practice</h2><span className="text-xs text-ink-faint">Recent completed attempts</span></div><ol className="divide-y divide-line">{attempts.slice(0,12).map(attempt => <li key={attempt.id}><Link href={`/quizzes/${attempt.quiz.id}/results?attempt=${attempt.id}`} className="flex flex-wrap items-center gap-3 py-4"><span className="min-w-0 flex-1 break-words text-sm">{attempt.quiz.title}</span><span className="text-xs text-ink-faint">{attempt.completedAt && formatRelativeTime(attempt.completedAt)}</span><span className="w-16 text-end font-mono text-sm">{attempt.score}/{attempt.totalQuestions}</span><ArrowUpRight className="h-4 w-4 text-ink-faint" /></Link></li>)}</ol><p className="mt-5 text-xs text-ink-faint">Quiz comparisons use your latest 40 completed attempts. Scores show performance on those questions, not a measure of everything you know.</p></section>}
    </>}
  </PageShell>;
}
