"use client";
import { useState } from "react";
import { ArrowRight, Check, FileText, Layers3, ListChecks, RotateCcw, X } from "lucide-react";
import { cn } from "@/lib/utils";

const stages = [{ label: "Capture", icon: FileText }, { label: "Understand", icon: Layers3 }, { label: "Practice", icon: ListChecks }, { label: "Remember", icon: RotateCcw }];

export function LearningExample() {
  const [stage, setStage] = useState(0);
  const [answer, setAnswer] = useState<number | null>(null);
  const [revealed, setRevealed] = useState(false);
  return <div className="learning-example">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-5 py-4 sm:px-7"><span className="index-label">A little learning, in action</span><span className="text-xs text-ink-faint">Interactive example</span></div>
    <div className="grid grid-cols-4 border-b border-line" role="group" aria-label="Explore the learning journey">{stages.map((item, index) => <button key={item.label} type="button" aria-pressed={stage === index} onClick={() => setStage(index)} className={cn("relative flex min-h-20 flex-col items-center justify-center gap-2 px-1 text-[11px] sm:text-xs", stage === index ? "bg-accent-soft font-semibold text-ink" : "text-ink-soft hover:bg-surface-muted")}><item.icon className="h-4 w-4" />{item.label}{stage === index && <span className="absolute inset-x-0 bottom-0 h-0.5 bg-action" />}</button>)}</div>
    <div className="min-h-[330px] px-6 py-7 sm:min-h-[350px] sm:px-9" aria-live="polite">
      <p className="index-label mb-5">Biology / The making of a memory</p>
      {stage === 0 && <><div className="mb-5 inline-flex items-center gap-2 border border-line bg-paper px-3 py-2 text-xs text-ink-soft"><FileText className="h-4 w-4" />lecture-notes.md</div><h2 className="font-display text-2xl">How memories take shape</h2><p className="mt-4 text-sm leading-[1.9] text-ink-soft">When we learn, connections between neurons change. Recalling an idea strengthens those connections. <mark className="bg-accent-soft px-1 text-ink">Returning to it over time</mark> helps the memory last.</p><p className="mt-5 border-s-2 border-line-strong ps-3 font-display text-base italic text-ink-soft">A source is the beginning of understanding.</p></>}
      {stage === 1 && <><h2 className="font-display text-2xl">Make the connections.</h2><p className="mt-3 text-sm leading-relaxed text-ink-soft">A study guide gives your material a shape.</p><div className="mt-6 space-y-4">{[["01", "Encoding", "Taking in and processing new information."], ["02", "Consolidation", "Stabilizing a memory over time."], ["03", "Retrieval", "Bringing stored information back to mind."]].map(([number, title, text]) => <div key={number} className="flex gap-4"><span className="pt-0.5 font-mono text-xs text-accent-dark">{number}</span><div><h3 className="text-sm font-semibold">{title}</h3><p className="mt-1 text-xs leading-relaxed text-ink-soft">{text}</p></div></div>)}</div></>}
      {stage === 2 && <><h2 className="font-display text-xl sm:text-2xl">What brings a stored memory back to mind?</h2><fieldset className="mt-5 space-y-2"><legend className="sr-only">Choose an answer</legend>{["Encoding", "Retrieval", "Consolidation"].map((option, index) => <button key={option} onClick={() => setAnswer(index)} aria-pressed={answer === index} className={cn("flex min-h-11 w-full items-center gap-3 rounded-control border px-3 text-left text-sm", answer === index ? index === 1 ? "border-success bg-success/10" : "border-danger bg-danger/10" : "border-line hover:border-line-strong")}><span className="font-mono text-xs text-ink-faint">{String.fromCharCode(65 + index)}</span>{option}{answer === index && (index === 1 ? <Check aria-label="Correct answer" className="ms-auto h-4 w-4 text-success" /> : <X aria-label="Incorrect answer" className="ms-auto h-4 w-4 text-danger" />)}</button>)}</fieldset>{answer !== null && <p role="status" className={cn("mt-4 text-sm", answer === 1 ? "text-success" : "text-danger")}>{answer === 1 ? "Correct. Retrieval is the act of recalling stored information." : answer === 0 ? "Incorrect. Encoding takes in new information. Try again." : "Incorrect. Consolidation stabilizes a memory over time. Try again."}</p>}</>}
      {stage === 3 && <><p className="mb-4 text-xs text-ink-faint">Recall before you reveal.</p><h2 className="font-display text-2xl">What is retrieval?</h2><div className="mt-6 min-h-24 border-s-2 border-accent ps-4">{revealed ? <p className="text-base leading-relaxed">Bringing stored information back to mind. Each recall is another chance to strengthen the connection.</p> : <p className="font-display text-lg italic text-ink-soft">Give your memory a moment.</p>}</div><button onClick={() => setRevealed(!revealed)} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-control bg-action px-4 text-sm text-action-foreground">{revealed ? "Try recalling again" : "Reveal the answer"}<ArrowRight className="h-4 w-4" /></button></>}
    </div>
    <div className="flex items-center justify-between gap-3 border-t border-line bg-paper/60 px-6 py-4"><span className="text-xs text-ink-soft">Same material. A deeper understanding.</span><span className="font-mono text-xs text-accent-dark">0{stage + 1} / 04</span></div>
  </div>;
}
